name: flutter_task
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  go_router: ^15.1.1
  cached_network_image: ^3.4.1
  injectable: ^2.5.0
  get_it: ^8.0.3
  json_annotation: ^4.9.0
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  dartz: ^0.10.1
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_gen:
  injectable_generator: ^2.6.2
  json_serializable: ^6.8.0

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_28pt-Bold.ttf
        - asset: assets/fonts/Inter_28pt-ExtraLight.ttf
        - asset: assets/fonts/Inter_28pt-Medium.ttf
        - asset: assets/fonts/Inter_28pt-Regular.ttf
        - asset: assets/fonts/Inter_28pt-SemiBold.ttf
        - asset: assets/fonts/Inter_28pt-thin.ttf

flutter_gen:
  output: lib/core/presentation/utils/generated/generated_assets/
  integrations:
    flutter_svg: true
