// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiBy8rV-dVnM8ovdtXbThxQYh6rmcPMGA',
    appId: '1:840023823019:web:f025fda973fa9c64b39dee',
    messagingSenderId: '840023823019',
    projectId: 'fluttertask-55702',
    authDomain: 'fluttertask-55702.firebaseapp.com',
    storageBucket: 'fluttertask-55702.firebasestorage.app',
    measurementId: 'G-DDEDK0HRR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR9-07PfjjU0zyndVUc1YYLzWiDpyZ-Zw',
    appId: '1:840023823019:android:9a26fa40248062a1b39dee',
    messagingSenderId: '840023823019',
    projectId: 'fluttertask-55702',
    storageBucket: 'fluttertask-55702.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn_w3vHkwVs7-m53MM3-XQdPlnUUQkb5g',
    appId: '1:840023823019:ios:eff8829aacbcd3abb39dee',
    messagingSenderId: '840023823019',
    projectId: 'fluttertask-55702',
    storageBucket: 'fluttertask-55702.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAn_w3vHkwVs7-m53MM3-XQdPlnUUQkb5g',
    appId: '1:840023823019:ios:eff8829aacbcd3abb39dee',
    messagingSenderId: '840023823019',
    projectId: 'fluttertask-55702',
    storageBucket: 'fluttertask-55702.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiBy8rV-dVnM8ovdtXbThxQYh6rmcPMGA',
    appId: '1:840023823019:web:1fa630f4e94d526bb39dee',
    messagingSenderId: '840023823019',
    projectId: 'fluttertask-55702',
    authDomain: 'fluttertask-55702.firebaseapp.com',
    storageBucket: 'fluttertask-55702.firebasestorage.app',
    measurementId: 'G-3GJSNZX6PH',
  );
}
